### ISSUE TITLE
Error in JS

### ISSUE THREAD

**Issue by chadsterBAM** [janizde/WP-Opening-Hours#10]
TypeError: undefined is not a function (evaluating 'dateStart.datepicker')

    dateStart.datepicker({
      dateFormat: 'yy-mm-dd',
      onClose: function (date) {
        dateEnd.datepicker("option", "minDate", date);
      }
    });

Line 265. This is on the FRONT end.  I was under the assumption that the js for datepicker wouldn't show on the front end at all.

**Comment by janizde** [comment]
has this been fixed by https://github.com/janizde/WP-Opening-Hours/pull/11 ?
