### ISSUE TITLE
schema.org support

### ISSUE THREAD

**Issue by janizde** [janizde/WP-Opening-Hours#104]
Check support for multiple periods per day in the schema.org spec again and then add the corresponding markup to the plugin templates

https://wordpress.org/support/topic/schema-org-caching-and-wpml/

> Regardings schema.org-markup: I think you can use the meta tag here to insert mutiple time slots per day (see first answer here: https://stackoverflow.com/questions/17058982/different-type-of-openinghours-per-day-using-schema-org).

**Comment by rvencu** [comment]
Thanks. I made my own schema.org plugin for a medical clinic. Opening hours are important and currently I set them manually in schema org. It would be nice to be able to replace the functions I made with automated ones and have a centralized place to manage opening hours.

**Comment by janizde** [comment]
Hi @rvencu 
I am currently working on the feature, you can track the progress in the branch: https://github.com/janizde/WP-Opening-Hours/tree/feature/schema.org

**Comment by rvencu** [comment]
Great, I am set to test your code on my data on a special test page template. If I will have issues with the result I can make that page password protected and share the password here for further testing

**Comment by janizde** [comment]
With quite a delay it's now ready with version 2.2.0
