### ISSUE TITLE
Sporadic hours on Saturdays

### ISSUE THREAD

**Issue by rvencu** [janizde/WP-Opening-Hours#106]
Hi, I have some sporadic hours on Satudays. We are treating patients on Saturdays only if they make an appointment with the doctors (so both agree to meet on Saturday). Not every Saturday is a working day and which Saturday is and which is not is impredictible.
This sound a lot like irregular hours but I cannot seem to find a proper way to implement it.
Did you encountered such a situation elsewhere? If yes how did you treat it?

**Comment by janizde** [comment]
Hi @rvencu yes that should be possible using irregular openings:

* Do not set any regular opening hours for saturday
* Add irregular openings only on the saturdays (specify the date) when you are open
* In the overview you will then have to set the shortcode option `include_io` to make the table show the irregular openings
