### ISSUE TITLE
Overview, Week offset, Child Set issue.

### ISSUE THREAD

**Issue by AndyMcLean005** [janizde/WP-Opening-Hours#108]
Bit of a weird one, but I'm currently working on displaying the current week's opening times and next week's opening times. The current week re-opens a little later in the afternoon but has the same morning opening time, so requires a child set as the io option only allows for 1 opening time per date. The week after is business as usual. However both overviews show the child set opening times.

Suggestion: I feel this issue could be resolved by allowing and displaying multiple irregular opening times under a single label.

I've attached some images of my issue. Image 1 shows the normal set of opening hours. Image 2 shows the child set. Image 3 shows the result when adding two widgets, one showing this week, and one showing a week offset of "1". The end date on image 2 ends on the Sunday before the offset week begins where the opening times return to normal.
![1](https://user-images.githubusercontent.com/39263666/39997857-348811ec-577c-11e8-8b14-00423869332a.jpg)
![2](https://user-images.githubusercontent.com/39263666/39997870-3b5141f6-577c-11e8-998d-3ea13404da0f.jpg)
![3](https://user-images.githubusercontent.com/39263666/39997874-402470fe-577c-11e8-9710-798fa67f530c.jpg)

**Comment by AndyMcLean005** [comment]
To add to this, this issue only appears while the child is active. If I set the child to next week, then display next week's opening hours, it still shows the parent set's hours. 

It only shows the child set's hours while the child set is active.

**Comment by janizde** [comment]
Hi @AndyMcLean005 this is a misconception on how child sets take effect. It is already filed in https://github.com/janizde/WP-Opening-Hours/issues/102 and will be part of a major refactoring in 3.0. but this will probably take some time. I will close this one as the feature is already requested.
