### ISSUE TITLE
Adding custom templates and attributes (Feature request)

### ISSUE THREAD

**Issue by Stender89** [janizde/WP-Opening-Hours#109]
It Would be fantastic to be able to code your own templates and attributes - 
Ie. I have a template for only showing the weekdays, and one for the weekends - 
But to be able to do this, I have to go into your classes/module/shortcode/overview.php
and add it to the $templateMap array.
This way I can add new valid template-attributes to the shortcodes.
like : [op-overview etc etc template="yourCustomTemplateHere"]

Custom hooks and filters to add such things, would open up the plugin.
As would being able to overwrite the normal templates in your theme directory - 
But it seems like it is constricted to only check itself.

I know you don't have much time for the plugin anymore,  
But the last update is over 6 months old, 
And I have had to resort to using a modified version, so that I could use some of the good stuff lying in the next versions. 
like "show holiday name when closed" which I have not had a problem with in months 👍

**Comment by janizde** [comment]
Hi, I have actually started to do a refactoring on how shortcodes a exptensible but I think this will be part of a major version change. I will maybe add a simple filter to the current version as you suggested. I will keep you updated. There will maybe be an update coming this weekend including the schema.org feature and the filter.

**Comment by janizde** [comment]
As this is already filed in this feature request I will close this issue: https://github.com/janizde/WP-Opening-Hours/issues/77
