### ISSUE TITLE
More Settings 

### ISSUE THREAD

**Issue by maxime057** [janizde/WP-Opening-Hours#113]
Bonjour le bouton "More Settings" ne fonctionne pas rien ne ce passe j'ai essayer sur plusieurs navigateur cela ne change rien :/ 
Pourriez-me fournir une solution merci par avance ;)

Maxime ^^

**Comment by Stender89** [comment]
For the rest of the world : 
___
Hello the button "More Settings" does not work nothing happens I try on several browsers it does not change anything: /
Could you give me a solution thanks in advance;)

Maxime ^^

**Comment by maxime057** [comment]
thank you xP ;)

**Comment by Stender89** [comment]
you might want to check your js console for errors - if nothing happens when you press the button, it could suggest that you have a JS conflict. 

Also, it will be easier for people to help you, if you give them more information.

Good luck 👍

**Comment by maxime057** [comment]
source code of button "<a class="collapse-toggle">More Settings</a>"
source code of section hidden "<div class="settings-container hidden">"
I have not seen an error in the console Js
I managed a little wild by changing the source code in live of the page to make the changes

**Comment by janizde** [comment]
Maybe some strange plugin combination is preventing the widget initialized event from being fired. Have you experienced any other JS related issues with other plugins? What WP version are you using?
