### ISSUE TITLE
Month Overview?

### ISSUE THREAD

**Issue by aapco** [janizde/WP-Opening-Hours#114]
I'm working on a project and I LOVE this plugin!  My client has requested a calendar view whereby they can page thru months and view the open hours for the month in a table-like layout.  Ideally I'd like to be able to show multiple sets for each day (i.e. restaurant and bar hours on one calendar).  It sounds like this would require a completely new shortcode since the current "overview" focuses on a week view and only one set.  I suppose it would be possible to display a month by looping thru and incrementing the week offset.  Or perhaps looping thru the days of the month and retrieving the hours for each day.  Any direction you can provide would be greatly appreciated.

**Comment by janizde** [comment]
Hi, you can have a look at the developer guide where you can see how to get the data programatically: https://github.com/janizde/WP-Opening-Hours/blob/master/doc/developer-guide.md With this data you can then implement your own shortcode. You might also be interested in the `OverviewModel` class which is capable of merging holidays and irregular openings in the regular opening hours flow.

Let me know if you have any further questions.
