### ISSUE TITLE
Add check for is_array in Overview shortcode

### ISSUE THREAD

**Issue by janizde** [janizde/WP-Opening-Hours#119]
`$row['items']` is either an array, a holiday object or an irregular opening object. Calling `count` with a non-array and non-Countable triggers a warning in PHP 7.2.

Before calling `count`, an `is_array` check should be done.

https://github.com/janizde/WP-Opening-Hours/blob/8aa0d2a786ae7910d5cddc618dc502962b085f43/classes/OpeningHours/Module/Shortcode/Overview.php#L114

**Comment by ash-tsc** [comment]
HI, hilfe! Kann ich Dich gegen eine Spende motivieren das Problem zu beheben? 
Wir würden gern Ausnahmen und Ferien Optionen verwenden können. Danke!  
[http://snap.ashampoo.com/mibYZi40r5GtQv5YCUq8bL4GMDQq8fElNFEiobHA8oTpErIHGzgHgdOthaEFFjQt](url)
[https://wordpress.zoum.de/start-testseite-mit-widget/](url)

Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/w011cae2/wordpress.zoum.de/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/Shortcode/Overview.php on line 114

**Comment by ash-tsc** [comment]
siehe auch:
https://wordpress.org/support/topic/overview-php-error/

**Comment by ash-tsc** [comment]
Bitte, bitte, bitte fix diesen Fehler! Ich spendiere Dir auch gern was für Deinen Aufwand! Ich würde so gern diese wunderbare Software verwenden. Aber egal ob ich Widgets oder Shortcodes verwende. In Kombi mit Ausnahmen und Urlaub funktioniert nichts mehr. :( 
![kaputt](https://user-images.githubusercontent.com/16594981/58877786-ee8cc300-86d1-11e9-8c8b-d1c1dc34f5e3.jpg)

**Comment by janizde** [comment]
@ash-tsc I will have a look into this on the weekend. The donations are on a voluntary basis so I would like to stress that no one has to pay anything for a bug fix.

**Comment by ash-tsc** [comment]
Thank you! Let me know how I can donate and if I can help to test new builds,

**Comment by misagues** [comment]
Hi @ash-tsc 
> Let me know how I can donate

[Donate](https://github.com/janizde/WP-Opening-Hours#donate)

**Comment by ash-tsc** [comment]
Hi, 
Thank you! BR,
