### ISSUE TITLE
White Screen Error

### ISSUE THREAD

**Issue by rowaboat** [janizde/WP-Opening-Hours#12]
Currently getting a white screen of death error when installing the version from http://www.jannikportz.de/2015/04/20/opening-hours-2-0-beta-please-test/ 

I'm using php 5.5.11 and Wordpress 4.2.2.

**Comment by janizde** [comment]
Please test it again with beta2 http://bit.ly/2bco9AZ

**Comment by janizde** [comment]
@rowaboat please verify whether this issue is still present with beta3 otherwise I will close this issue
