### ISSUE TITLE
[enhancement] op-overview without past weekdays and show_next all time ranges

### ISSUE THREAD

**Issue by luckhavemh** [janizde/WP-Opening-Hours#120]
Hello janizde,
first of all i want to thank you for your fantastic plugin.
I have 2 questions or suggestions for your plugin.

Is it possible to hide passed days in the op-overview table and replace these opening hours of passed days with the upcoming opening hours of the next week, if there are changes.

And how can i let the plugin show me the next opening periode including all time ranges of all periods on that upcoming day. 
Right now, its just showing me the time ranges of the first period, but not the 2. period on that day. It would be nice, if it showed the %1$s of the today_format class.

Thank you for your help and your work here.

**Comment by janizde** [comment]
Hi @luckhavemh,
sorry for the late reply. If you're still interested in it, there are some possible solutions that require custom code (filter hooks)

https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_overview_model

* The weekday thing: You can use the [`op_overview_model` filter hook](https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_overview_model) for this. You can then implement a class that extends [`OverviewModel`](https://github.com/janizde/WP-Opening-Hours/blob/master/classes/OpeningHours/Module/Shortcode/OverviewModel.php) whose `getData()` resp. `getCompressedData()` method returns the data you want. You could possibly make this class take an `OverviewModel` of the current week and an `OverviewModel` of the next week and then merge these two according to the current weekday in `getData()`
* Custom next period message with all periods of the day: You can use the [`op_is_open_format_next` filter](https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_is_open_format_next) for this. The filter function will get the `$todayData` as the fourth argument which contains all of the periods, holidays and irregular openings on that day

**Comment by ash-tsc** [comment]
Sorry, custom code obviously is too much for my small old not web coder brain to grasp. I wonder if @luckhavemh was able to solve the 1. and 2. period of the day riddle and display complete working hours with a break in between ?
