### ISSUE TITLE
Able to change color of Open/Close?

### ISSUE THREAD

**Issue by will2383** [janizde/WP-Opening-Hours#124]
I thought I saw this in the documentation when I first started using this a few years ago, but I can't find it now.  Is it possible to define the color of the "today" period?  i.e. if open it's a green, if closed it's a red.  I'd like to customize that, is there a shortcode modifier to use to do so?

**Comment by janizde** [comment]
Hi, the plugin hardly provides any styling except the static colors for red and green. For custom style you will have to provide your own CSS. The elements should be selectable by class names. To disable all of the styling you can use the [`op_use_front_end_styles`](https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_use_front_end_styles) filter
