### ISSUE TITLE
The date format doesn't adapt on frontend

### ISSUE THREAD

**Issue by HelmutGoebel** [janizde/WP-Opening-Hours#127]
I changed the date format in the list of holidays. It does change in the backend. But it remains in the frontend.

**Comment by janizde** [comment]
Hi @HelmutGoebel , are you referring to a shortcode or a widget? Could you paste the shortcode you're using or the configuration settings of the widget?

**Comment by HelmutGoebel** [comment]
Widget. I've deactivated the plugin.
