### ISSUE TITLE
week_offset doesn't check for child sets

### ISSUE THREAD

**Issue by makkabi** [janizde/WP-Opening-Hours#129]
Assuming that this week the "summer" opening hours are in effect, and starting next week the winter opening hours (as defined in a child set of the summer opening hours) will be in effect. If I use the shortcode op-overview and set week_offset to 1, it still displays the summer opening hours. The week_offset parameter doesn't use the child set that will actually be in effect next week. It only seems to check if there is a "irregular opening" defined in the summer (parent) opening hours, and will display them correctly if there are any.

**Comment by janizde** [comment]
Yeah you're right the child set only kicks in when the criteria matches *the current date*. This is a misconception that can hardly be circumvented in the close future but will definetely be considered for the major refactoring of opening data model starting soon. For now I can just close this but will flag this as a use case for 3.0
