### ISSUE TITLE
want to change some icons

### ISSUE THREAD

**Issue by moinabbasqureshi** [janizde/WP-Opening-Hours#130]
hi, 
I want to change 'Closed' and 'Open' name that display in frontend.  I want to change these names, but i didnot find anything related to that. Please guide me

**Comment by ElectricFeet** [comment]
Hi @moinabbasqureshi If you use the [shortcode builder](https://janizde.github.io/opening-hours-shortcode-builder/), it guides you through how to build a shortcode with the text you want.

**Comment by janizde** [comment]
As @ElectricFeet pointed out it's best to go with the shortcode builder which is now also integrated in the set edit page (*Create a Shortcode* link). You can also refer to the docs here:https://github.com/janizde/WP-Opening-Hours#shortcodes
