### ISSUE TITLE
Widgets / plugin uses site's locale, not user's locale

### ISSUE THREAD

**Issue by ElectricFeet** [janizde/WP-Opening-Hours#132]
On the back end, the Opening Hours plugin incorrectly uses the site's locale rather than the user's.

For example, I'm designing an Italian site, but Italian is my second language. My mother tongue is English. I work 10 times slower in Italian than I do in English. The site needs to be in Italian, of course. Since WP 4.7, WordPress allows the user to set their own language in the user profile. Mine is set to GB English, but in the context of this bug, I tried both en_US and en_GB: the results are the same.

This is what I see with the Opening Hours widget:

<img width="779" alt="Screenshot 2020-01-05 at 21 08 27" src="https://user-images.githubusercontent.com/6003638/71785424-9dde9f00-2fff-11ea-9f2a-509aa3ccf6a7.png">

You can see on the left, the choice of WordPress/other plugin's widgets are  in English apart from the Opening Hours widget. In addition, the Opening hours widget panel texts are all Italian. (Both with the exception of a few strings that haven't been translated yet.)

It looks like the plugin is picking up the **_site's_** locale (which in my case is Italian), not the **_user's_** locale.

I'm not sure how to fix the plugin, but the details on user locales are here: https://make.wordpress.org/core/2016/11/07/user-admin-languages-and-locale-switching-in-4-7/

**Comment by janizde** [comment]
Thanks for the extensive explanation, I will take a look

**Comment by janizde** [comment]
Fixed in https://github.com/janizde/WP-Opening-Hours/commit/6f4ab8df50da21d6c53ec7bec9ec3b76bd9b207c will be part of 2.2.1 

Thanks for reporting!

**Comment by ElectricFeet** [comment]
Hi @janizde . I spoke too soon. I just spotted that the backend panel is still in the site's locale, rather than the user's.

Screenshots:

<img width="317" alt="Screenshot 2020-01-20 at 19 01 25" src="https://user-images.githubusercontent.com/6003638/72748378-605d4280-3bb7-11ea-80f2-6afeb9f3300a.png">
<img width="303" alt="Screenshot 2020-01-20 at 18 59 13" src="https://user-images.githubusercontent.com/6003638/72748385-62bf9c80-3bb7-11ea-8cdd-6c2ffd81d34e.png">
