### ISSUE TITLE
Got a fatal error on updating to action scheduler 3.0

### ISSUE THREAD

**Issue by ajgw** [janizde/WP-Opening-Hours#133]
Hi, have updated woocommerce subscriptions to version 3.0 which brought us action scheduler 3 with it. At migrating of action scheduler actions I got a fatal error from Opening Hours Plugin:

2020-01-09T08:41:16+00:00 CRITICAL Uncaught TypeError: Argument 2 passed to OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox::saveDataCallback() must be an instance of WP_Post, null given, called in /…/wp-includes/class-wp-hook.php on line 288 and defined in /…/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/CustomPostType/MetaBox/AbstractMetaBox.php:77
Stack trace:
#0 /…/wp-includes/class-wp-hook.php(288): OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox->saveDataCallback(114269, NULL, true)
#1 /…/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /…/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /…/wp-includes/post.php(4120): do_action('save_post', 114269, NULL, true)
#4 /…/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/CustomPostType/MetaBox/AbstractMetaBox.php in Zeile 77

After data migration all seems to be fine and no more errors.

**Comment by janizde** [comment]
Hi @ajgw ,

the method you mentioned is implemented against the API of the `save_post` action hook. In [the specification](https://developer.wordpress.org/reference/hooks/save_post/) you can see that it is said to be provided the `$post_ID` and the `WP_Post $post` as second parameter. In your setup there seems to be one module (maybe woocommerce or action scheduler?) that invokes this hook incorrectly, so I suspect the issue to be not in the opening hours plugin.

As this only occurred once during the migration progress, I'd close this issue now. If it is urgent you might want to reach out to woocommerce.
