### ISSUE TITLE
Please provide example function on how to return a set opening/closing times as php or json array | object

### ISSUE THREAD

**Issue by monecchi** [janizde/WP-Opening-Hours#136]
I've been trying to understand how the plugin API works, but I'm getting a real bad time trying to achieve the following:

I need to create a function which will return a Set opening/closing times times by id or name alias... The function should then return the data as as php or json array | object. I'd to localize that as js object on my WordPress theme.

	use OpeningHours\Entity\Set;
	use OpeningHours\Module\OpeningHours;
	use OpeningHours\Entity\Period;

	function my_op_getSet($setID) {

		$hours = array();

		$openingHours = OpeningHours::getInstance();

		$set = $openingHours->getSet($setID);

		$dateObject = current_datetime(); 
		$timezoneSTring = 'America/Sao_Paulo'; // custom timezone string as current_datetime()->timezone returns an integer

		// debug
		//var_dump($dateObject);

		$now = new \DateTime($dateObject->date, new \DateTimeZone($timezoneSTring));
		var_dump($now);

		$data = $set->getDataForDate($now);

		foreach ($data['periods'] as $period) {
			$hours['periodos'] = $period;
		}
		$hours[]['isOpen'] = $set->isOpen($now) ? 'open' : 'closed';

		// debug
		var_dump( $hours );

		return $hours;
	}

The function returns nothing but the isOpen status:  

	array(2) {
		["periodos"]=>
		string(2) "{}"
		[0]=>
		array(1) {
			["isOpen"]=>
			string(6) "closed"
		}
	}

How could one actually get the set opening/closing time with php? Any help is really appreciated. Thanks in advance.

**Comment by janizde** [comment]
Hi, in the loop you're reassigning the same `periodos` key over and over again causing only the last period to be set there. To collect all of them you would have to add to the array. I don't quite know why you're just getting the `{}` string. You could try to access the start and end dates programatically, so for example

```php
$hours['periods'] = [];
foreach ($data['periods'] as $period) {
  $hours['periods'][] = [
    'start' => $period->getStart(),
    'end' => $period->getEnd(),
  ];
}

```

**Comment by monecchi** [comment]
Thanks @janizde for getting by. Actually I made a mistake referencing the function above, what i really wanted was to get the opening / closing times by calling `$data = $set->getPeriods($now)` instead of `$data = $set->getDataForDate($now)`, ...

Here's the output of the function above for a specific set id... The issue I think is that I'm not so good at php programming to deal with those array of objects iteration... Getting stuck again, debugging it but WP throwing errors...

I wish there was an easy way of getting that kind of data format with a simpler function/filter, but I'm glad I found your plugin, it is really promising!


	object(DateTime)#20015 (3) {
		["date"]=>
		string(26) "2020-11-03 00:00:00.000000"
		["timezone_type"]=>
		int(3)
		["timezone"]=>
		string(17) "America/Sao_Paulo"
	}

	OpeningHours\Util\ArrayObject Object
	(
		[storage:ArrayObject:private] => Array
			(
				[0] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 0
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-15 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-16 00:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
				[1] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 1
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-16 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-17 00:30:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
				[2] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 2
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-17 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-18 00:30:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
				[3] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 3
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-11 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-12 00:30:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
				[4] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 4
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-12 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-13 00:30:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
				[5] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 5
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-13 00:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-13 00:30:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 
						[dummy:protected] => 
					)
	
				[6] => OpeningHours\Entity\Period Object
					(
						[weekday:protected] => 6
						[timeStart:protected] => DateTime Object
							(
								[date] => 2020-03-14 18:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[timeEnd:protected] => DateTime Object
							(
								[date] => 2020-03-15 01:00:00.000000
								[timezone_type] => 3
								[timezone] => UTC
							)
	
						[spansTwoDays:protected] => 1
						[dummy:protected] => 
					)
	
			)
	
	)

**Comment by janizde** [comment]
What errors is it throwing? You can easily convert an `ArrayObject` to an array using [`ArrayObject::getArrayCopy()`](https://www.php.net/manual/en/arrayobject.getarraycopy.php) if that helps you.

**Comment by monecchi** [comment]
I'll try to manage that out.  Thanks.

I'm also getting an error while trying to supply `$now` by using WP default functions such as the following:

    $timezoneSTring = 'America/Sao_Paulo';
    $now = new \DateTime( wp_date( get_option('date_format'), time() ), new \DateTimeZone($timezoneSTring));
    $data = $set->getDataForDate($now);



Uncaught Error: Call to a member function getDataForDate() on null in /var/www/...theme_filters.php:251 where the mentioned function is placed...

**Comment by janizde** [comment]
Some points to help with this:

1. You can ask the Dates util for `$now` with `OpeningHours\Util\Dates::getNow()` it should have the correct timezone already
2. The `SetProviders` are intialized on the `init` filter hook so make sure that when calling your function you do this not earlier than `init` with a priority > 10 like

```php
add_action('init', function () {
  my_op_getSet(1);
}, 11);
```

**Comment by monecchi** [comment]
Thanks for following up @janizde !

I got it working with your help! Now I can use my own function to output the opening / closing times as json / localized data for a given set id... That helped me a lot on creating a custom WP REST API endpoint function so I can retrieve it easily everywhere.

For those who might come looking for the same answer, here's the final function:

    use OpeningHours\Entity\Set;
    use OpeningHours\Module\OpeningHours;
    use OpeningHours\Entity\Period;
    use OpeningHours\Util\Dates;

    function my_op_getSet($setID) {

        global $wp_locale;

        $hours = array();

        $openingHours = OpeningHours::getInstance();

        $set = $openingHours->getSet($setID);
        
        $now = Dates::getNow();

        $data = $set->getPeriods($now);

        $day_of_week = $datetime->format('l'); // (string) - "wednesday"
        $day_of_week_number = intval( $datetime->format('w') ); // (int) number - 3

        /**
         * Output all regular opening hour periods
         */
        $hours['periods'] = [];
        foreach ($data as $key => $period) {

            $week_day_slug = $wp_locale->get_weekday( $period->getWeekday() );

            $hours['today'] = [ 'name' => __( ucfirst( $day_of_week ), 'domain' ), 'number' => $day_of_week_number, 'slug' => $wp_locale->get_weekday( $datetime->format( 'w' ) ) ];

            $hours['periods'][] = [
                'weekday' => array( 'name' => __( ucfirst( $wp_locale->get_weekday( $period->getWeekday() ) ), 'domain' ), 'name_abbrev' => $wp_locale->get_weekday_abbrev( $week_day_slug ), 'slug'=> $week_day_slug, 'number' => $period->getWeekday() ),
                'start' => $period->getTimeStart(),
                'end' => $period->getTimeEnd(),
            ];
        }
        $hours[]['isOpen'] = $set->isOpen($now) ? 'open' : 'closed';

        return json_decode(json_encode($hours), true);
    }


And here's the function output: 

    {
    "opening_hours": {
        "periods": [{
            "weekday": {
                "name": "Sunday",
                "name_abbrev": "sun",
                "slug": "sunday",
                "number": 0
            },
            "start": {
                "date": "2020-03-15 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-16 00:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Monday",
                "name_abbrev": "mon",
                "slug": "monday",
                "number": 1
            },
            "start": {
                "date": "2020-03-16 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-17 00:30:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Tuesday",
                "name_abbrev": "tue",
                "slug": "tuesday",
                "number": 2
            },
            "start": {
                "date": "2020-03-17 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-18 00:30:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Wednesday",
                "name_abbrev": "wed",
                "slug": "wednesday",
                "number": 3
            },
            "start": {
                "date": "2020-03-18 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-19 00:30:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Thursday",
                "name_abbrev": "thu",
                "slug": "thursday",
                "number": 4
            },
            "start": {
                "date": "2020-03-19 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-20 00:30:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Friday",
                "name_abbrev": "fri",
                "slug": "friday",
                "number": 5
            },
            "start": {
                "date": "2020-03-20 00:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-20 00:30:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        },
        {
            "weekday": {
                "name": "Saturday",
                "name_abbrev": "sat",
                "slug": "saturday",
                "number": 6
            },
            "start": {
                "date": "2020-03-14 18:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            },
            "end": {
                "date": "2020-03-15 01:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
            }
        }],
        "today": {
            "name": "Saturday",
            "number": 6,
            "slug": "saturday"
        },
        "0": {
            "isOpen": "closed"
        }
    }
    }

**Comment by janizde** [comment]
👍
