### ISSUE TITLE
Opening Hours: Is Open Status - Naming Collision

### ISSUE THREAD

**Issue by andyeder** [janizde/WP-Opening-Hours#138]
In the Opening Hours: Is Open Status widget, the settings form consists of two input fields (**Class for span** and **CSS Classes**) that share the same 'id' and 'name' attributes.

As a consequence, when saving the settings, any value entered in field **Class for span** is overwritten by the value found in the **CSS Classes** field.

![bug](https://user-images.githubusercontent.com/14290788/79669085-09183f80-81b1-11ea-95a0-e6c125fd80a7.png)

**Comment by janizde** [comment]
Hi @andyeder , I'm wondering where the last option *CSS classes* comes from? It's not part of the Widget shipped with the plugin.

**Comment by andyeder** [comment]
Hi @janizde , the **CSS Classes** option appears to be a standard setting across all Wordpress widgets. If you navigate into the Appearance->Widgets section of the Wordpress dashboard and setup a widget area (by inserting a selection of widgets into that area) you will find that each widget has the CSS Classes option as the last option.

**Comment by janizde** [comment]
Are you sure this is not coming from a third party plugin like this: https://de.wordpress.org/plugins/widget-css-classes/ ? Can you please check your installed plugins?

**Comment by andyeder** [comment]
Yes, I will take another look. I recently picked up this project from another developer and am still familiarising myself with it. Please give me a moment to check... thanks for your patience.

**Comment by andyeder** [comment]
@janizde - please accept my apologies, it is indeed a problem with the Widget CSS Classes third-party plugin. I will remove that plugin and refactor the project.

Thanks for your patience and time and - again - my apologies.

**Comment by janizde** [comment]
No biggie :) Thanks for submitting, I will considered prefixing all of them in a future release.
