### ISSUE TITLE
*Sugestion*

### ISSUE THREAD

**Issue by wato1987** [janizde/WP-Opening-Hours#15]
Wondering if someone can help me and also like to sugest 

a way i can op-overview but for the next week

so op-overview + 7 ?

**Comment by janizde** [comment]
@wato1987 implemented, release in v2.1

**Comment by sorenk** [comment]
Is this going to be a variable? So I can set it to 3 weeks or even more?
Does this also include the possibility to change the format on the days shown in the op-overview output, so it for instance could include a date instead of a weekday?

**Comment by janizde** [comment]
@sorenk You can test the dev version by downloading from https://downloads.wordpress.org/plugin/wp-opening-hours.zip this is the RC unless there are any significant bugs

**Comment by janizde** [comment]
released in v2.1
