### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#17]
The last commits are updates to a new version?

I tried to combine the new with v2.0 files, but do not work. throw a lot of mistakes.

Thanks

**Comment by janizde** [comment]
I'm currently working on it and rearranging some classes etc. I have not tested it yet and it's not even finished but i will inform you when the new Version is ready to use (in beta).

**Comment by misagues** [comment]
I hope really excited.

 If you allow me a suggestion, it would be perfect translate the months from the .po language file.

 Thank you.

**Comment by janizde** [comment]
Aren't they included in the translations? Actually all language-specific strings should be translatable. Could you please tell me where it's not translated?

**Comment by misagues** [comment]
Hi,

Weeks are present in the .po language file between the lines 154 and 208. But the months do not appear.

Thanks.

**Comment by misagues** [comment]
Hi,

Weeks are present in the german .po language file between the lines 178 and 232. But the months do not appear.

Thanks.

**Comment by janizde** [comment]
Ah, I see. All appearances of month names come from formatting a date using the date($format, $time) method. I will have a look how I can improve this to also include in the translation set

**Comment by misagues** [comment]
Thanks.

**Comment by janizde** [comment]
The month names are now taken from the WP core translations depending on the locale, so the month names won't be in the .pot but translated.

fixed in dea819c71c7a10dd51e8afae32eecae4c23426d1

**Comment by janizde** [comment]
beta 2 is now available! http://bit.ly/2bco9AZ
