### ISSUE TITLE
Deleting a holiday

### ISSUE THREAD

**Issue by lorro** [janizde/WP-Opening-Hours#2]
Just tried to delete the holiday I previously added, so there should be no holiday anymore and I get the following error.

`Catchable fatal error: Argument 1 passed to OpeningHours\Module\CustomPostType\MetaBox\Holidays::filterPostConfig() must be of the type array, null given, called in /home/srdev/public_html/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/CustomPostType/MetaBox/Holidays.php on line 94 and defined in /home/srdev/public_html/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/CustomPostType/MetaBox/Holidays.php on line 115`

**Comment by janizde** [comment]
fixed in 165fe01e7f7793f745b96ee8fb842cf631701982
