### ISSUE TITLE
Error by activation

### ISSUE THREAD

**Issue by foomep** [janizde/WP-Opening-Hours#22]
I use this plug-in in version 1.2 on WP 4.5 on two installation.
The First is a Host Europe Server an it works perfectly. The second installation is uberspace Server an i get an Error:
`Das Plugin verursachte 2635 Zeichen unerwartete Ausgabe während der Aktivierung. Solltest du Fehlermeldungen wie „headers already sent“, Probleme mit der Syndizierung der Feeds oder andere Fehler erhalten, versuche, das Plugin zu deaktivieren oder zu löschen.`

with a strange code in the front:
<img width="1680" alt="bildschirmfoto 2016-04-15 um 11 59 10"src="https://cloud.githubusercontent.com/assets/4090141/14558226/874f7cac-0301-11e6-9630-4d0a4726ea1f.png">

What can i do to activate the plug-in?

**Comment by misagues** [comment]
Make a test with version 2.0 beta

http://www.jannikportz.de/2015/04/20/opening-hours-2-0-beta-please-test/

**Comment by foomep** [comment]
ohh yes. the version 2.0 beta work great, thx. I have only a few of issues, I open them again.
