### ISSUE TITLE
delete a opening hours weekdate

### ISSUE THREAD

**Issue by foomep** [janizde/WP-Opening-Hours#24]
If I delete the Saturday and the Sunday and update, they appears after the update again with 0:00 - 0:00.

**Comment by misagues** [comment]
I do not understand what you want to say.
Show me a screenshot or the error in a test site.

**Comment by foomep** [comment]
A question before: That means when I choose a day from 0:00 to 0:00 the day is closed? Or should I delete the time?

If 0:00 to 0:00 is a closed day, the widget setting "Show closed days" dosn't work. The closed days appear always.

**Comment by misagues** [comment]
I do not use this function because I want to appear closed days. But actually, I've tried and does not work.
This is a beta version.
Jannik is preparing an update that will change many things. We will wait to see if resolved in the new version.
Your interim solution seems appropriate.

**Comment by foomep** [comment]
Its a beta version, so I sages it.
offtopic: I'm new on github. can I lable this issue?

**Comment by misagues** [comment]
http://www.jannikportz.de/2015/04/20/opening-hours-2-0-beta-please-test/

**Comment by janizde** [comment]
sorry for being so late
the 00:00 to 00:00 periods will not be considered as real periods the bug was indeed that the show_closed option didn't work.

fixed in 49e0d0679cdb1e5632e51d73f9507bca9c5331e7
