### ISSUE TITLE
Bug with Customizer

### ISSUE THREAD

**Issue by foomep** [janizde/WP-Opening-Hours#25]
If I activate the plug-in and go to the Customizer, the site can't load:
<img width="1679" alt="bildschirmfoto 2016-04-21 um 10 06 08" src="https://cloud.githubusercontent.com/assets/4090141/14702093/e2c9df0e-07a8-11e6-863f-2380f4ab4ffe.png">

I deactivate the plug-in and it works.

**Comment by misagues** [comment]
Yes, the problem comes from update Wordpress 4.
I disable the plug-in to use the customizer.
The customizer not used every day.

**Comment by foomep** [comment]
Yes, so I do it well

**Comment by janizde** [comment]
may this be related to https://github.com/janizde/WP-Opening-Hours/issues/26 ?
