### ISSUE TITLE
The plugin break the editor after update wordpress 4.5.2 ==SOLVED==

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#26]
Hi,

when will the next version for use or test?

In v2.0 the plugin break the editor after update wordpress 4.5.2.

For write in posts, pages, etc is need deactivate the plugin.

You know a solution?

Thanks.

**Comment by misagues** [comment]
SOLVED.

Update the library URL Jquery in \classes\OpeningHours\OpeningHours.php to solve the problem with the editor in version 4.5.2

Change URL jQuery in line 114.
http://code.jquery.com/ui/1.10.4/jquery-ui.min.js ==>> http://code.jquery.com/ui/1.11.4/jquery-ui.min.js

**Comment by janizde** [comment]
fixed in 1181e56413e78aa99ed1dc41ae4a4ab004c56031
thanks for reporting I will release the next beta tomorrow
