### ISSUE TITLE
Date Picker wrong

### ISSUE THREAD

**Issue by Happyfeet01** [janizde/WP-Opening-Hours#29]
Hello,

can you Update the Date Picker?
When i choose th correct Day e.g. Monday to Sunday are Holidays. It shows at the Frontpage Monday - Saturday. 
Also the Datepicker begins with Sunday. Can i change this?

**Comment by janizde** [comment]
Does it set the correct date in the inputs when you used the datepicker? Or does the value in the input match the selected date in the datepicker?
In how far does it display Mon - Sat, when including it in the Overview table?
I will make the plugin aware of the "Week starts on" WordPress setting, Thank you!

**Comment by Happyfeet01** [comment]
the Datepicker shows the first day as an Monday 
![datepicker](https://cloud.githubusercontent.com/assets/3295104/18410529/ef1275aa-7765-11e6-8630-3643c4515dd2.png)

it would be nice if you can update it. Timezone on Server and Wordpress is correct.

**Comment by janizde** [comment]
I updates the datePickers to always use the WordPress Setting now f76d512e74db67b82b42c7930f3b96b2fd787dbe
However in the Widget it will still always start on Monday, I'll fix that

**Comment by Happyfeet01** [comment]
Thanks

**Comment by Happyfeet01** [comment]
is that normal when i try to activate the latest ZIP
? 

> Warning: require_once(includes/admin-notice-helper/admin-notice-helper.php): failed to open stream: No such file or directory in /var/www/vhosts/cloud-surfer.eu/blog.cloud-surfer.eu/wp-content/plugins/WP-Opening-Hours-master/wp-opening-hours.php on line 18

**Comment by janizde** [comment]
@Happyfeet01 No that shouldn't happen. Please have a look if the file actually exists. I should be shipped with the pre-build zip. If it exist please add the __DIR__ constant in the path as done in 4a450947353fdcd84b86bc02afc6085884474dbf

**Comment by janizde** [comment]
@Happyfeet01 the Overview widget is now also aware of the start_of_week setting in commit 4ff5f337b733f8464663a2fbf8d1d5c840788378 (still in develop branch)
