### ISSUE TITLE
Various bugs with beta2

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#30]
1 * The green and red colors do not appear in the open and closed states.
![img_20160906_063258](https://cloud.githubusercontent.com/assets/16360881/18261867/c0969466-73fc-11e6-87cf-01375779f1f7.jpg)

2 * In set opening hours floating calendar/time picker does not appear. You must enter date and time manually.
![img_20160906_062819](https://cloud.githubusercontent.com/assets/16360881/18261914/1ef044c6-73fd-11e6-80c8-23a8e072afd3.jpg)
![img_20160906_062826](https://cloud.githubusercontent.com/assets/16360881/18261913/1eeff962-73fd-11e6-8c6b-cba80d860264.jpg)

3 * I can not add opening hours in the afternoon. Pressing "+" does not work.
![img_20160906_062753](https://cloud.githubusercontent.com/assets/16360881/18261946/5d2cc58e-73fd-11e6-8c4e-c5a204c639e8.jpg)

4 * The Irregular Openings not saved.

 5* In the Widgets, does not work "More Settings".
![img_20160906_062650](https://cloud.githubusercontent.com/assets/16360881/18262012/f1a3c604-73fd-11e6-9905-12ee79f0a680.jpg)
![img_20160906_062708](https://cloud.githubusercontent.com/assets/16360881/18262013/f1a57bca-73fd-11e6-921f-bdae77b6070a.jpg)

6 * In Overview Widget, if I select "Highlight - Running Period" white screen appears on the web.

Thanks.

**Comment by janizde** [comment]
Most of this looks like the CSS and JS of the Plugin is not loading. How have you installed the beta version? When cloning or downloading from github you will have to build the assets first before being able to use it.
You can also download a built zip here http://bit.ly/2bpeeps
If you have actually used the built version please have a look at your console. Missing files are sometimes logged there. Thanks for your feedback

**Comment by Happyfeet01** [comment]
can you release a new Version to the Wordpress Plugin Site?

**Comment by janizde** [comment]
@Happyfeet01 this is still a beta release, I will add a new WordPress release when the beta phase has finished. However I will update the SVN trunk in the WordPress Plugin repository every once in a while but not after every change

**Comment by Happyfeet01** [comment]
@janizde I have download the built zip from the post but I can't add holidays or something else. Buttons don't work. I need this Plugin..

**Comment by martinlyder** [comment]
scripts and css referes to a non existing "dist"-folder: wp-opening-hours/dist/scripts/main.js?ver=2.0 and wp-opening-hours/dist/scripts/main.js?ver=2.0

**Comment by janizde** [comment]
oh I see, I've updated the file please try again

**Comment by janizde** [comment]
@misagues should work now with the new version (the dist/ directory must be inside the plugin).
6 should also work now.
please have a look at 4) and open a new issue if it still doesn't work

**Comment by janizde** [comment]
beta3 is now available please have a look: http://bit.ly/2e3c4QG

**Comment by janizde** [comment]
beta3 now available please have a look: http://bit.ly/2cTlMVu
