### ISSUE TITLE
Beta-2 dosen't show closed days

### ISSUE THREAD

**Issue by martinlyder** [janizde/WP-Opening-Hours#31]
I have placed the widgets and checked the Show closed days. But they dosen't show up...

**Comment by janizde** [comment]
has been fixed in 3992dcc8a062bc9b7f008e093f6a0b4609b26af6 will be available in the next beta release

**Comment by janizde** [comment]
beta3 now available should work now http://bit.ly/2e3c4QG
please have a look

**Comment by janizde** [comment]
beta3 is now available and it should work now http://bit.ly/2cTlMVu
please have a look
