### ISSUE TITLE
Check if the store is open or closed through PHP?

### ISSUE THREAD

**Issue by fakeartist** [janizde/WP-Opening-Hours#32]
Can someone please help me with this? With the old version I used the function is_open(), but now the function does not exist. Any alternative way?

**Comment by janizde** [comment]
You need to know the Set id and can then retrieve the Set by using the OpeningHours module singleton instance e.g.
```php
$module = OpeningHours\Module\OpeningHours::getInstance();
$set = $module->getSet(3); // When Set id is 3
$set->isOpen() // returns bool
```
