### ISSUE TITLE
Fatal error in beta3

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#33]
I downloaded the plugin 2.0 beta 3 to the http://bit.ly/2dwbnNi.

I did a clean install of wordpress.

I installed the plugin.

I activated the plugin.

I went to the section of the plugin and when click in add new, get a fatal error.

![error_add_new_set](https://cloud.githubusercontent.com/assets/16360881/19136915/6b4be6ce-8b70-11e6-8aba-73d69e838a11.JPG)

And you can not continue.

**Comment by Happyfeet01** [comment]
Have the same error when I try to add a new set. 

```
Error thrown

Call to a member function getPeriods() on null
```

**Comment by janizde** [comment]
Ooops I have uploaded a revision in the blog.

**Comment by misagues** [comment]
give me a download link for testing.

**Comment by janizde** [comment]
should be the same link, I have uploaded a revision on Google Drive

**Comment by Happyfeet01** [comment]
Hi,

I re-download this Plugin and it was successfull updated on the homepage. 
It works really good.

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 6. Oktober 2016 1:19:07 nachm. schrieb Ramiro Rosa 
<notifications@github.com>:

**Comment by misagues** [comment]
Perfect!
Gone is the error.
But now we have the problem #34
