### ISSUE TITLE
Irregular Openings disappears in beta3

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#34]
I have done a test updating the existing plugin in a site.

At first glance all one right. have respected the times set, configuring the widgets, etc.

But I enter my Hours Set, I make a change for test and push update changes; then all settings irregular openings disappears.

**Comment by janizde** [comment]
Could you please describe the Irregular Opening problem a bit more precisely? Are the Irregular Openings not saving?

**Comment by misagues** [comment]
Add irregular openings.
![error_add_irregular_openings_01](https://cloud.githubusercontent.com/assets/16360881/19153564/5c1e373a-8bd7-11e6-9f46-f8ec91d114ba.JPG)

Pulse to publish or update.
![error_add_irregular_openings_02](https://cloud.githubusercontent.com/assets/16360881/19153691/d036ae04-8bd7-11e6-99fb-a8e3cf8d9260.jpg)


irregular openings disappear.
![error_add_irregular_openings_03](https://cloud.githubusercontent.com/assets/16360881/19153692/d5eb92ba-8bd7-11e6-8f38-ee325b44ac66.jpg)

**Comment by janizde** [comment]
could you please comment out lines 71, 74 and 76 in classes/OpeningHours/Module/CustomPostType/MetaBox/IrregularOpenings.php and then try again to see whether there's an error?

**Comment by misagues** [comment]
when I comment out lines 71, 74 and 76 and push update returns the following error:

**Fatal error**: Uncaught exception 'InvalidArgumentException' with message '$date is not in valid date format' in C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Entity\IrregularOpening.php:62 Stack trace: #0 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings.php(72): OpeningHours\Entity\IrregularOpening->__construct('Prueba', NULL, '10:00', '13:30') #1 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings.php(54): OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings->getIrregularOpeningsFromPostData(Array) #2 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox.php(82): OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings->saveData(4, Object(WP_Post), true) #3 [internal function]: OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox->saveDataCallback(4, Object(WP in **C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Entity\IrregularOpening.php** on line **62**

![error_add_irregular_openings_04](https://cloud.githubusercontent.com/assets/16360881/19158577/930d8022-8be9-11e6-83eb-08f7fc21a097.jpg)

**Comment by janizde** [comment]
Thank you, it's probably related to the datepicker.
Please have a look in your console if there are any errors and put a `var_dump($_POST)` before line 53

**Comment by misagues** [comment]
array(55) { ["_wpnonce"]=> string(10) "1a5eb4e4ea" ["_wp_http_referer"]=> string(44) "/testwp/wp-admin/post.php?post=4&action=edit" ["user_ID"]=> int(1) ["action"]=> string(8) "editpost" ["originalaction"]=> string(8) "editpost" ["post_author"]=> int(1) ["post_type"]=> string(6) "op-set" ["original_post_status"]=> string(7) "publish" ["referredby"]=> string(69) "http://elportal.dyndns.dk/testwp/wp-admin/post.php?post=4&action=edit" ["_wp_original_http_referer"]=> string(69) "http://elportal.dyndns.dk/testwp/wp-admin/post.php?post=4&action=edit" ["post_ID"]=> string(1) "4" ["meta-box-order-nonce"]=> string(10) "94b04d1f24" ["closedpostboxesnonce"]=> string(10) "4f97d3d173" ["post_title"]=> string(7) "Horario" ["samplepermalinknonce"]=> string(10) "508621d22a" ["op_meta_box_set_details_nonce"]=> string(10) "bbfc26237b" ["op_meta_box_set_details"]=> array(1) { ["description"]=> string(0) "" } ["wp-preview"]=> string(0) "" ["hidden_post_status"]=> string(7) "publish" ["post_status"]=> string(7) "publish" ["hidden_post_password"]=> string(0) "" ["hidden_post_visibility"]=> string(6) "public" ["visibility"]=> string(6) "public" ["post_password"]=> string(0) "" ["mm"]=> string(2) "10" ["jj"]=> string(2) "06" ["aa"]=> string(4) "2016" ["hh"]=> string(2) "15" ["mn"]=> string(2) "17" ["ss"]=> string(2) "23" ["hidden_mm"]=> string(2) "10" ["cur_mm"]=> string(2) "10" ["hidden_jj"]=> string(2) "06" ["cur_jj"]=> string(2) "06" ["hidden_aa"]=> string(4) "2016" ["cur_aa"]=> string(4) "2016" ["hidden_hh"]=> string(2) "15" ["cur_hh"]=> string(2) "20" ["hidden_mn"]=> string(2) "17" ["cur_mn"]=> string(2) "00" ["original_publish"]=> string(10) "Actualizar" ["save"]=> string(10) "Actualizar" ["menu_order"]=> string(1) "0" ["post_name"]=> string(7) "horario" ["op_meta_box_opening_hours_nonce"]=> string(10) "667aa0dd30" ["opening-hours"]=> array(7) { [1]=> array(2) { ["start"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(5) "16:00" } ["end"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(5) "20:00" } } [2]=> array(2) { ["start"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(5) "16:00" } ["end"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(5) "20:00" } } [3]=> array(2) { ["start"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(5) "16:00" } ["end"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(5) "20:00" } } [4]=> array(2) { ["start"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(5) "16:00" } ["end"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(5) "20:00" } } [5]=> array(2) { ["start"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(5) "16:00" } ["end"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(5) "20:00" } } [6]=> array(2) { ["start"]=> array(1) { [0]=> string(5) "00:00" } ["end"]=> array(1) { [0]=> string(5) "00:00" } } [0]=> array(2) { ["start"]=> array(1) { [0]=> string(5) "00:00" } ["end"]=> array(1) { [0]=> string(5) "00:00" } } } ["op_meta_box_holidays_nonce"]=> string(10) "795881cdb0" ["opening-hours-holidays"]=> array(3) { ["name"]=> array(2) { [0]=> string(21) "DÃ­a de la Hispanidad" [1]=> string(24) "DÃ­a de Todos los Santos" } ["dateStart"]=> array(2) { [0]=> string(10) "2016-10-12" [1]=> string(10) "2016-11-01" } ["dateEnd"]=> array(2) { [0]=> string(10) "2016-10-12" [1]=> string(10) "2016-11-01" } } ["op_meta_box_irregular_openings_nonce"]=> string(10) "c0f5274f0b" ["opening-hours-irregular-openings"]=> array(3) { ["name"]=> array(2) { [0]=> string(6) "Prueba" [1]=> string(0) "" } ["timeStart"]=> array(2) { [0]=> string(5) "10:00" [1]=> string(0) "" } ["timeEnd"]=> array(2) { [0]=> string(5) "13:30" [1]=> string(0) "" } } [""]=> array(1) { ["date"]=> array(2) { [0]=> string(10) "2016-10-08" [1]=> string(0) "" } } ["post_mime_type"]=> string(0) "" ["ID"]=> int(4) ["comment_status"]=> string(6) "closed" ["ping_status"]=> string(6) "closed" } 
Fatal error: Uncaught exception 'InvalidArgumentException' with message '$date is not in valid date format' in C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Entity\IrregularOpening.php:62 Stack trace: #0 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings.php(73): OpeningHours\Entity\IrregularOpening->__construct('Prueba', NULL, '10:00', '13:30') #1 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings.php(55): OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings->getIrregularOpeningsFromPostData(Array) #2 C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox.php(82): OpeningHours\Module\CustomPostType\MetaBox\IrregularOpenings->saveData(4, Object(WP_Post), true) #3 [internal function]: OpeningHours\Module\CustomPostType\MetaBox\AbstractMetaBox->saveDataCallback(4, Object(WP in C:\xampp\htdocs\testwp\wp-content\plugins\opening-hours\classes\OpeningHours\Entity\IrregularOpening.php on line 62

**Comment by misagues** [comment]
![error_add_irregular_openings_05](https://cloud.githubusercontent.com/assets/16360881/19169052/f9965b74-8c12-11e6-94bd-b64c3228122b.jpg)

**Comment by janizde** [comment]
thank you, fixed in c3f638316bb531bc666d21caff5a9169ebb7475d
I have updated the file on Google Drive and the change is on master now

**Comment by misagues** [comment]
Tested and working.

Thanks.
