### ISSUE TITLE
holidays in red

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#35]
How can you put the names of the holidays in red as the closed days?

![festivos_en_rojo_](https://cloud.githubusercontent.com/assets/16360881/19246830/8fcd0120-8f28-11e6-9037-4ba3df687698.jpg)

Thanks!

**Comment by janizde** [comment]
makes sense, I will add this. Thank you!

**Comment by misagues** [comment]
In Widget Opening Hours: Overview?

**Comment by janizde** [comment]
yes I will add the closed-style to Holidays in the Overview

**Comment by janizde** [comment]
added this in 32d273ad42a5cde9804a5575fb0a4113359fe40e

**Comment by misagues** [comment]
It works perfect.
Thank you!
