### ISSUE TITLE
the translation in the plugin does not work

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#36]
I finished to translating the plugin to Spanish in:
https://translate.wordpress.org/locale/es/default/wp-plugins/wp-opening-hours

I followed your instructions to install the translation in the plugin:
> 3.- In the line below the legend, select all current as Machine Object Message (.mo) and click Export.
> 4.- Rename the file to wp-opening-hours-{locale}.mo (replace {locale} with the actual locale of the translation, in my case es_ES leaving the file as well: wp-opening-hours-es_ES.mo).
> 5.- Move the file to /path/to/wordpress/wp-content/plugins/wp-opening-hours/language

but the text strings are not translated.

I tried to rename the file with all the variations that have occurred me. E.g.:
es_ES.mo
es.mo
wp-opening-hours-es_ES.mo
wp-opening-hours-es.mo
wp-opening-hours.mo
opening-hours-es_ES.mo
opening-hours-es.mo
opening-hours.mo
wp-opening-hours-dev-es_ES.mo
etc.

Thanks!

**Comment by misagues** [comment]
I have translated the file wp-opening-hours.pot of beta 3 with Poedit, I have uploaded the files .mo and .po to /language directory and renamed (es_ES and all variants), and does not work.

**Comment by foomep** [comment]
I had the same problem and I solved it by copying the .mo file to path/to/wordpress/wp-content/languages.

**Comment by misagues** [comment]
With  wp-opening-hours-de_DE.mo it not works me.
thanks

**Comment by janizde** [comment]
@foomep this is actually a better idea to place it in the wp-content/languages. I will do some research on placing mo files there and then update the docs

**Comment by misagues** [comment]
@foomep your idea has helped me.
 I solved it by copying the .mo file to path/to/wordpress/wp-content/languages**/plugins** as wp-opening-hours-es_ES.mo

Thanks

**Comment by janizde** [comment]
@foomep @misagues thank you I will update the docs

**Comment by janizde** [comment]
I have updated the documentation on this topic in e8e4343a2424eb802bc9bfa2f170a95615cc9d4b

**Comment by misagues** [comment]
The translation process does not work properly in WordPress 4.5.x. Text strings remain untranslated.

In WordPress 4.6.x it works correctly.

**Comment by janizde** [comment]
@misagues you're right, this behavior only works automatically since WP 4.6, I have added backwards compatibility in d0e7e22936e84ae9354dddaae39f95bd93d7a853
Place try again with the latest develop

**Comment by misagues** [comment]
I tried the added and it works great.

only does not translate the area "Set Details"

![set_details_notraslate_wp4 5 x](https://cloud.githubusercontent.com/assets/16360881/19754615/5608f6bc-9c0f-11e6-9559-e652ec4469a8.JPG)

but it is a less important thing.

Thanks!

**Comment by misagues** [comment]
When you go to update the file on Google Drive with all the latest fixes?

Thanks!
