### ISSUE TITLE
Show Set Description in widget Opening Hours: Overview. Checkbox does not work

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#37]
If the set we write a description appears in the widget is checked or not the box.

![show_set_description_03](https://cloud.githubusercontent.com/assets/16360881/19396829/3a692338-9245-11e6-85b7-cd458f11cb0d.jpg)

![show_set_description_02](https://cloud.githubusercontent.com/assets/16360881/19396838/423acb5c-9245-11e6-958b-7c2b6a3ddb31.jpg)

![show_set_description_01](https://cloud.githubusercontent.com/assets/16360881/19396845/46608a32-9245-11e6-8ceb-5cc8a72743ee.jpg)

Thanks!

**Comment by janizde** [comment]
tank you, fixed in f58438cee1643e8057a64e862700c3d28b217dd8

**Comment by misagues** [comment]
It works perfect.
Thank you!
