### ISSUE TITLE
Fatal Error since update to v 2.0

### ISSUE THREAD

**Issue by richardfantom** [janizde/WP-Opening-Hours#38]
Hi, I hope this is constructive and helps you with a bugfix. My simple Wordpress site was using the previous version of Opening Hours but since update to 2.0 there is a fatal error report. I deleted then reinstalled the plug-in but with the same result.

Plugin could not be activated because it triggered a fatal error.
Catchable fatal error: Argument 2 passed to OpeningHours\Module\Ajax::addAction() must be an instance of OpeningHours\Module\callable, array given, called in /home/sites/[***]/public_html/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/Ajax.php on line 97 and defined in /home/sites/[***]/public_html/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Module/Ajax.php on line 127

**Comment by janizde** [comment]
Thank you, you are probably running on PHP 5.3 aren't you? I figured out that the `callable` is only available on PHP >=5.4 didn't know that and my IDE didn't warn me. I will fix this asap

**Comment by janizde** [comment]
I have fixed this in 76773ef7b06662999f36d662acff676647b5eef5
and the updated version is in the wordpress plugin repository (still tagged as 2.0) so you might manually download it from there and push it to wp-content/plugins

**Comment by richardfantom** [comment]
You are right. My installation was running php 5.3 and I wondered if this was the cause so updated to 5.5 but can't recall whether I did this before or after I reinstalled Opening Hours. I'll manually reinstall from the repository and let you know if it works smoothly. Cheers.
