### ISSUE TITLE
Whats the right format to create a shortcode

### ISSUE THREAD

**Issue by zaasrvr** [janizde/WP-Opening-Hours#39]
Hello,

I start using this wp plugin days ago. Im not using the widget. Im using the following code:

[op-overview set_id="80"]

Can you explain to me how to add "show_closed_days" to this line of code in the right format? 

sorry im no a coder

Thanks

Alex

**Comment by janizde** [comment]
Hi @zaasrvr you can add more parameters like `[op-overview set_id="80" show_closed_days="true"]`
