### ISSUE TITLE
Next open-period doesn't seem to be right

### ISSUE THREAD

**Issue by lorro** [janizde/WP-Opening-Hours#4]
I setup the opening hours of a particular day (tuesday, as it is today) from 7:30 to 16:30. The current time is 17:00.

The is-open widget states that the venue is currently closed: so far so good. But the indication of the next open period seems to be somewhat off. It says the following

`We will be open on tuesday (28 april 2015) from 7:30 to 16:30.`

That's quite odd as that's the date of today. I would reckon this should gave me the opening hours of the next day in line, namely wednesday i.e. tomorrow?

**Comment by janizde** [comment]
Please test it again with beta2 http://bit.ly/2bco9AZ
