### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by lfrohling** [janizde/WP-Opening-Hours#44]
Could you add example lines on how EXACTLY to use the shortcodes in the HTML please. Simply having the tables with things like set_id and other info in other cells like title doesn't tell beginnners how to USE the shortcodes. Do they type things like [opening_hours_set_id_title_true] or what? 

Without basic usage information and examples on what text to embed into the code all that shortcode information is useless.

Thanks,
Luke

**Comment by janizde** [comment]
I will add basic reference and examples and a link to the WordPress docs on shortcodes to the docs.

**Comment by gegeor** [comment]
Hello
I also  have  problem with  undersanding  the exact  syntax of shortcodes...Is there any kind  of  exact  examples  for  shortcodes?

thank you

**Comment by janizde** [comment]
Hi @gegeor, Shortcodes are a core component of WordPress. You can read about them here: https://codex.wordpress.org/Shortcode_API With the Plugin you would have to replace the Shortcode tag and set the attriubutes you want listed in the docs. I will add examples in the docs soon.

**Comment by janizde** [comment]
I have added general doc on shortcodes, will come in 2.1

**Comment by gegeor** [comment]
Hi
thats great news!!!!!
Thank you:)
