### ISSUE TITLE
*Suggestion* Could be nice to have isOpen show todays opening hours

### ISSUE THREAD

**Issue by martinlyder** [janizde/WP-Opening-Hours#47]
Hi
It could be nice that the isOpen widget had a feature to show todays opening hours and on holidays shows "Closed". 
Often shopping center sites, have "Opening Hours Today: 10:00 -19:00" Displayed in ex. the header..

Examples:
http://shopcapitalcitymall.com/directory
http://friisaalborg.dk <- here i tweeked your plugin to do that, but not in a nice way, therefor i write this suggestion :)

**Comment by janizde** [comment]
implemented, will come in 2.1

**Comment by janizde** [comment]
released in v2.1
