### ISSUE TITLE
Holiday with more than one consecutive date don't merge in shorten opening hours

### ISSUE THREAD

**Issue by martinlyder** [janizde/WP-Opening-Hours#48]
Hi 
if i have three holiday dates after each (ex. friday, saturday, sunday)  and have a widget where Shorten Openging hours is turn on. The output is not merged as "Friday - Sunday"... But writes it underneeth eachother.

**Comment by janizde** [comment]
@martinlyder I can't reproduce this behavior, please check again and specify whether you have any Irregular Openings or so

**Comment by martinlyder** [comment]
I think it refers to a old beta version... Im Closing this now...
