### ISSUE TITLE
Sort Irregular Openings and Holiday overview

### ISSUE THREAD

**Issue by jgudde** [janizde/WP-Opening-Hours#54]
Hi,

Love your plugin!

Is it possible to automatically sort the Irregular Openings overview [op-irregular-openings] on date starting with the earliest date? And I have the same request for the Holiday overview [op-holidays]. 

If this is not possible, is there a way to easily sort (or manage) the order of the overview?

Many thanks!

**Comment by janizde** [comment]
implemented, will be released in next update

**Comment by misagues** [comment]
Yes!
Works in version 2.1 rc

**Comment by janizde** [comment]
released in v2.1
