### ISSUE TITLE
Automatically hide past dates

### ISSUE THREAD

**Issue by jgudde** [janizde/WP-Opening-Hours#55]
Is there a way to automatically hide past Irregular Openings and Holidays in the overview [op-irregular-openings] and [op-holidays]?

Many thanks!

**Comment by janizde** [comment]
implemented, will be released in next update

**Comment by jgudde** [comment]
Many thanks! When will the update be released?

**Comment by janizde** [comment]
Propably on the weekend or so. You can already test the beta version by downloading from SVN trunk: https://downloads.wordpress.org/plugin/wp-opening-hours.zip

**Comment by misagues** [comment]
Yes!
Works in version 2.1 rc

**Comment by janizde** [comment]
released in v2.1
