### ISSUE TITLE
"Crash" with child sets

### ISSUE THREAD

**Issue by peterhjalmarsson** [janizde/WP-Opening-Hours#56]
When I add a child set, I get
`Warning: trim() expects parameter 1 to be string, object given in /storage/content/09/4001809/naturumdalarna.se/public_html/wp-includes/class-wp-meta-query.php on line 597 Catchable fatal error: Object of class WP_Post could not be converted to string in /storage/content/09/4001809/naturumdalarna.se/public_html/wp-content/plugins/wp-opening-hours/classes/OpeningHours/Entity/PostSetProvider.php on line 180`

Without child set it works fine. Also, the child set works fine if I convert it to a regular set. I'm from Sweden, so using date format "Y-m-d" if that matters?

**Comment by janizde** [comment]
@peterhjalmarsson fixed in v2.0.5
