### ISSUE TITLE
opening hours say open when closed

### ISSUE THREAD

**Issue by bommelmans** [janizde/WP-Opening-Hours#58]
i have set the plugin like this
opening hours 08:00 - 20:00
but at 20:30 it still say we are open....

and also i can't figure it out how to setup the 24 hours system
now i have in my site : 08:00 - 08:00 

hope you can help me with this

**Comment by janizde** [comment]
Hi @bommelmans I have just released a fix that would make it work with UTC offset timezones. Please check your WP Timezone Setting with both UTC offset and City if it works now

**Comment by janizde** [comment]
@bommelmans Please check again, otherwise I will close this one.
