### ISSUE TITLE
*Suggestion* feature request

### ISSUE THREAD

**Issue by waynep16** [janizde/WP-Opening-Hours#6]
How about... one more parameter to add to set, so we have OPEN and CLOSED

I want to show a message "Closing soon" and if time is within one hour, the message will show :+1: 

I think this would be a nice touch

**Comment by janizde** [comment]
I have added a today's opening times to is-open widget / shortcode. Will be released with 2.1. Although you cannot displays the "closing soon" message directly you can use the op_is_open_format_today filter to implement your custom behavior

**Comment by janizde** [comment]
released in v2.1
