### ISSUE TITLE
Months in English in Holidays Widget v2.1rc

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#66]
In the Holidays Widget the months are not translated correctly.

In the template "table" only translate correctly when they have the StartDate and the EndDate. In the new display option when the holiday period is only 1 day they are not translated.

![vista-tabla-opening-21](https://cloud.githubusercontent.com/assets/16360881/25648301/bd8f0a84-2fca-11e7-94ac-12764c5ac5d2.JPG)

In the template "list" never translate.

![vista-lista-opening-21](https://cloud.githubusercontent.com/assets/16360881/25648319/e10f9032-2fca-11e7-8291-033a76ad5a30.JPG)

**Comment by janizde** [comment]
released in v2.1
