### ISSUE TITLE
Child-Set überschreibt Ausnahmedatum

### ISSUE THREAD

**Issue by marvinschroeder** [janizde/WP-Opening-Hours#68]
Wenn man ein Ausnahmedatum im Eltern-Set festlegt und dieses dann durch ein Child-Set für einen bestimmten Zeitraum überschreiben lässt, ist das Ausnahmedatum nicht mehr in der Anzeige. Es ist quasi vollständig überschrieben.

Eltern-Set: Mo-Fr 8-12, Sonntag geschlossen
Ausnahme: Muttertag, Sonntag 8-12
Child-Set: im Monat März, April, Mai generell Mo-Fr 8-17, Sonntag geschlossen

Ohne das Child-Set wird die Ausnahme angezeigt. Mit Child-Set wird NUR das Child-Set genommen.

P.S.: Super Plugin! Daumen hoch!

**Comment by janizde** [comment]
fixed in d6c48e46712a975a7b3ae6ccb526873a3747eea7
will be released in hotfix v2.1.1

**Comment by janizde** [comment]
published in v2.1.1 https://github.com/janizde/WP-Opening-Hours/releases/tag/v2.1.1
