### ISSUE TITLE
Problems with irregular openings

### ISSUE THREAD

**Issue by BeingCreativeUs** [janizde/WP-Opening-Hours#69]
I updated it and in the beggining it seemed it was working fine, but on sunday we were open and the plugin stay showed we were closed and that we would open on next saturday, also, I tried the option of displaying the opening times always and isn't working, I have to use the "When is open" option, and I want to display it the entire day.  Maybe it has something to do with the fact that I use irregular openings?

Thank you,

**Comment by janizde** [comment]
Hi @BeingCreativeUs,
please specify the following so I can replicate the error better:

* Your WordPress timezone and start of week setting
* The Opening Hours and Irregular Openings you have set up and which caused the error.

Thank you

**Comment by BeingCreativeUs** [comment]
Hi Janizde,

Timezone: UTC +2 / Madrid
Start of week: Monday
Irregular openings: I attach a screenshot.
![irregular](https://cloud.githubusercontent.com/assets/28728339/26547626/31526bdc-4470-11e7-93b0-d70c965a2e5f.png)

Usually happens on sundays, and it just displays the next irregular opening (skipping the opening hours of the current day).

**Comment by janizde** [comment]
Oh I see you have a lot of irregular openings :) This also helps me to see how people are actually using the plugin, many thanks!

Do you have any regular opening hours set up or only irregular openings? When you say "skipping the opening hours of the current day" do you mean the regular opening hours or the irregular opening on sundays?

**Comment by BeingCreativeUs** [comment]
I only have the irregular openings. Also I have a child set of opening times for july and august because we open then everyday with the same schedule, I attach screenshot. Usually we open saturday and sunday, but some weekends we open more or less hours, that's why I don't have regular opening hours. When the plugin fails is usually on sundays. I don't know why. I tried to remove one and add it again and nothing. It just displays the next irregular opening, skipping sunday.

![screenshot_38](https://cloud.githubusercontent.com/assets/28728339/26561571/c54fd474-44bf-11e7-85c3-21ee65751597.png)
![screenshot_39](https://cloud.githubusercontent.com/assets/28728339/26561572/c553ebc2-44bf-11e7-9154-f0e121c705cf.png)

**Comment by misagues** [comment]
Hola @BeingCreativeUs,

Creo que tienes mal planteados los horarios en varias cosas, aunque sin conocer el caso real, tampoco estoy seguro.

Si los domingos los tienes todos definidos en aperturas irregulares no deberías poner un horario regular en los domingos.
También veo que defines algunos horarios de 19:00h a 01:00h, esto creo que puede estar mareando el plugin, ten en cuenta que las 01:00h es el día siguiente.

Lo correcto sería:
Lunes  00:00h a 01:00h y 19:00h a 00:00h
Martes 00:00h a 01:00h y 19:00h a 00:00h
etc.

Dices que solo tienes aperturas irregulares, pero en la tercera captura veo que tienes definido un horario regular.

Mi consejo; 
1.- Elimina todo.
2.- Realiza los horarios de nuevo con el siguiente planteamiento:
        - Haz un horario regular solo con los horarios y días con horarios fijos.
        - Haz aperturas irregulares para todas las variaciones y combinaciones.

Dinos a ver que tal.

**Comment by BeingCreativeUs** [comment]
Hola @misagues, creo que no has leído bien lo que he escrito anteriormente, quizá mi inglés no es lo suficientemente bueno. Esas aperturas regulares (captura 3) son un subconjunto, que se aplica solo desde el 1 de julio hasta el 3 de septiembre, y no debería afectar a las aperturas irregulares que tengo configuradas actualmente, ya que todavía estamos a 30 de mayo. Y el problema de tu sugerencia es que no me parece que quede bien que a partir de las 00:00h ponga "Hoy estamos abiertos de 00:00h a 01:00h". Igualmente, por el momento no tenemos ese horario, por lo tanto, eso no creo que esté causando el problema. Respecto a tus sugerencias, solo tenemos un horario regular en verano, por lo tanto, el resto del año son aperturas irregulares. Te dejo aquí una captura del calendario que tenemos en la web. Más que nada para que entiendas porque tengo así las aperturas irregulares.

![screenshot_3](https://cloud.githubusercontent.com/assets/28728339/26572099/ecb552a6-4518-11e7-8758-51921865b12d.png)

**Comment by misagues** [comment]
Hola @BeingCreativeUs,

Tranquilo que mi inglés tampoco es de Harvard.

Ok. Viendo el calendario veo tu problemática horaria y me he quedado un poco a cuadros.

Como aún te quedan 3 fines de semana "normales" yo haría lo que te dije en el anterior comentario; eliminaría todos los horarios y desde cero confeccionaría el actual como horario regular; configurando solo sábado y domingo.
Sábado 18:00h a 00:00h
Domingo 17:30h a 23:00h
Sin poner de momento ni irregulares ni nada y dejando de L a V también vacíos y comprobaría si te funciona bien.
El lunes, dependiendo del resultado (descartando la 1a parte) ya metería simulación con irregulares / conjuntos hijos para probar situaciones y poder ver como enfocar el "berenjenal" de horas que tienes.

En principio el plugin sale de la base que hay algunos días cerrados y algunos horarios irregulares, pero tu caso es todo lo contrario; la mayor parte del año está cerrado y todo o casi todo son aperturas irregulares. La verdad no sé como plantearía tu horario, hay muchas posibilidades, pero no sé cual sería la más adecuada al plugin para que este no pete.

Otra prueba que se me ocurre (volviendo a lo de las 01:00h), crea un horario regular con el horario que más días utilizas al año (19:00h a 01:00h), sin nada más y prueba a ver el domingo como actúa. Si te funciona bien, los otros días (que abres) los pondría como aperturas irregulares y todo el resto (los cerrados) como festivos; creo que sería el planteamiento más adecuado al plugin.

A ver si tienes suerte!!!

**Comment by BeingCreativeUs** [comment]
Hola @misagues,

Voy a hacer la última recomendación que me haces a ver si funciona bien.

Publicaré una respuesta cuando lo tenga hecho con una captura para que me indiques si está bien o no.

Un saludo.

**Comment by misagues** [comment]
Hola @BeingCreativeUs,

Haz una simulación este fin de semana a ver que tal.

Creo que el problema está al pasar de las 23:59h en un día. Acabo de ver otro caso parecido con el mismo problema.

Issue  #72 

Ya nos cuentas.

**Comment by BeingCreativeUs** [comment]
Hola @misagues,

Pero en caso de que fuera eso, no entiendo porque tiene que afectar ahora si no empezamos con ese horario hasta el 1 de julio.

Y aprovecho para sugerir que incluyáis un botón de duplicar apertura irregular, porque ahora que estoy volviendo a poner los horarios creo que sería muy útil para personas con el mismo problema que yo.

Un saludo.

**Comment by BeingCreativeUs** [comment]
Hola @misagues,

Aquí te dejo una captura de como ha quedado para que me indiques si es lo que me comentabas o no.
Lo probaremos a ver que tal este fin de semana y si funciona bien daremos por cerrado el tema.

Muchas gracias por tu ayuda,
Un saludo.

**Comment by janizde** [comment]
@misagues @BeingCreativeUs I have pointed out the bug and will try to fix and release it today.

Thanks for reporting and providing all of the information

**Comment by BeingCreativeUs** [comment]
Hey @janizde! So there's actually a bug and not bad configuration? Thank you for your help. Also in the previous post I made a suggestion, maybe you can include it in the update. The suggestion is that maybe the plugin could have a duplicate button on the irregular openings so people like me can add them quickly. Thank you so much.

**Comment by janizde** [comment]
@BeingCreativeUs I will release the bugfix as a patch version (where usually only bugfixes are included). Please open a new issue with the "enhancement" label, this will then maybe be implemented for v2.2

**Comment by BeingCreativeUs** [comment]
@janizde I already published it but I don't find how to add the label, so I guess you will have to. Thank you.

**Comment by janizde** [comment]
published in v2.1.1 https://github.com/janizde/WP-Opening-Hours/releases/tag/v2.1.1

**Comment by misagues** [comment]
Thanks for job @janizde 
love the plugin

**Comment by misagues** [comment]
Hola @BeingCreativeUs,
Como siempre @janizde se lo curra un montón para mantener su plugin actualizado y ha corregido el problema en cuanto ha podido.

Aparte de que el plugin tuviese el problema del salto de la medianoche, respecto al como plantear la distribución de tu horario, veo más correcta esta última configuración y, creo que, de cara a un futuro poder modificar horas lo tendrás más claro.

**>>** Si el plugin te gusta y te cubre la necesitad, por favor, [**haz una donación**](https://github.com/janizde/WP-Opening-Hours#donate) para que @janizde pueda seguir dedicando su tiempo en él.

Un saludo.
