### ISSUE TITLE
Another issue with irregular openings

### ISSUE THREAD

**Issue by mdbavister** [janizde/WP-Opening-Hours#72]
One of our locations has regular open hours = Mon-Thu 7:30-00:00 (midnight), Fri 7:30-18:00, Sat 12:00-18:00, and Sun 12:00-00:00. So far working great - until we had an exception for the US Memorial Day Holiday on Monday 5/29. The exception hours were 12:00-00:00, which again worked as expected on Monday. But today, Tuesday, our shortcode shows us as CLOSED today next open on Wednesday - instead of the correct normal hours of 7:30-00:00.

This bug only affects the op-is-open shortcode, seeming to ignore todays hours if the previous day exception bleeds past 23:59. I was able to replicate using test closing times. Here is our current code

[op-is-open set_id="library-1" show_today="open" show_next="true" today_format="Hours Today: %1$s"]

And the display is...

We're currently closed.
We're open again on Wednesday (May 31, 2017) from 7:30 am to 12:00 am

**Comment by janizde** [comment]
Hi @mdbavister, this is probably related to https://github.com/janizde/WP-Opening-Hours/issues/69

I have pointed out the bug and will try to fix and release it today.

Thank you

**Comment by janizde** [comment]
published in v2.1.1 https://github.com/janizde/WP-Opening-Hours/releases/tag/v2.1.1
