### ISSUE TITLE
Todays openinghours doesn't include holiday name

### ISSUE THREAD

**Issue by JesperStender** [janizde/WP-Opening-Hours#76]
When you set is-open to show_today="always" and there is a holiday, no text is shown - Should this not show the holiday name?

**Comment by misagues** [comment]
Hi @JesperStender.

Depending on your settings.

Do you use widget or shortcode?

To do what you want, with shortcode would be:

[op-is-open set_id="ID" show_today="always" closed_text="We're corrently closed"]

With shortcode would be:
See [Is Open Widget](https://github.com/janizde/WP-Opening-Hours#is-open-widget) documentation to configure.

**Comment by JesperStender** [comment]
I use the shortcodes - The thing is, that I need the same texts for open and closed - which is fine - This way, even though it is evening and the store is closed, it still says the opening hours for the current day. all that works fine - It is just that IF there is a holliday, then it just uses the "closed_text" and doesn't tell which holliday it is - there could be a setting to use the "holliday name" instead of todays hours.

Hard to explain

**Comment by Braunson** [comment]
@janizde I can add this feature in, mind adding the tag `Hacktoberfest` to it for me :) https://hacktoberfest.digitalocean.com/

**Comment by janizde** [comment]
added feature in https://github.com/janizde/WP-Opening-Hours/pull/98

**Comment by JesperStender** [comment]
Was this ever released? because I can't seem to find it?

**Comment by janizde** [comment]
@JesperStender it has been merged to develop but has not yet been released. I actually planned to add some more fixes to the patch release but it never happened. I will probably make a new patch for this one this week

**Comment by JesperStender** [comment]
sounds amazing! I incorporated the changed files yesterday, and it looks good! 
The only thing is, that if you have both a holiday and an irregular day on the same day, it will write both messages. 
So maybe that should be pointed out in the readme, or something :)
