### ISSUE TITLE
Wordfence plugin conflict

### ISSUE THREAD

**Issue by ClaudioQ** [janizde/WP-Opening-Hours#79]
After the installation of the version 2.1.1 of the plugin, accessing to Wordfence Live Traffic I wasn't able to access to the traffic list. I attached Wordfence 6.3.10 screenshot

![wordfence](https://cloud.githubusercontent.com/assets/26606009/26763845/deb750e6-495a-11e7-8871-669a2e9ccca0.jpg)

**Comment by janizde** [comment]
Hi @ClaudioQ, did this not happen wit v2.1 or any previous version?
Are there any errors in your Browser's console?

**Comment by ClaudioQ** [comment]
Hi @janizde, thanks for your support. I'm sorry, but I started using the plugin only from version 2.1.1, so I can not tell if this behavior occurs from this version or not.

I have verified, there are two problems with the javascritpt: enabling Opening Hours admin.liveTraffic.js doesn't work properly.
![errors_wordfence](https://cloud.githubusercontent.com/assets/26606009/26787259/a6017f7e-4a09-11e7-998b-a4621b59bf28.jpg)

**Comment by janizde** [comment]
Thanks I'll have a look

**Comment by janizde** [comment]
HI @ClaudioQ,
I have just had a look on it and figured out that Opening Hours and Wordfence use different jQuery UI Plugins that are sharing the same namespace and as a result are conflicting.
Unfortunately this is not something that can be fixed in a quick hotfix.
I will probably offer a solution to this in the next minor or major release.

**Comment by ClaudioQ** [comment]
Hi @janizde,
thanks for your support, so I'll wait your next release.

I also had a support request for the Wordfence team, I take the answer below in the hope that it may somehow become useful (otherwise please ignore it).

> Hi,
> It happens that some plugins load their resources on every page, this could cause such conflicts with other plugins using similar JS libraries, what I recommend here is reporting this issue to “Opening Hours” plugin’s author as I’m sure if he limits loading his plugin JS file “main.js” only on the plugin’s custom post type admin page, that would resolve this issue, this guide should be helpful in this case.
> 
> Thanks.

The guide is this link: https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts#Example:_Load_CSS_File_from_a_plugin_on_specific_Admin_Page

**Comment by janizde** [comment]
Oh yes I could actually do this as a quick fix :) I will release a patch in the next couple of days

**Comment by janizde** [comment]
I have fixed this one in v2.1.2 and released it to the WP repositories. Please update and check

**Comment by misagues** [comment]
Work!
WordPress 4.8 + Duplicator 2.1.2 + Wordfence 6.3.10 OK

Thanks @janizde
