### ISSUE TITLE
Is open now, bool

### ISSUE THREAD

**Issue by miloandco** [janizde/WP-Opening-Hours#80]
Is it not possible to just do a shortcode that returns a bool, whether it's currently open or not? without returning any output, except for the bool.

Could be usefull to show/hide a whole section, depending on the status.

**Comment by janizde** [comment]
Shortcodes cannot "return" anything explicitly they can only render content or not. However you can interact with the Opening Hours core programatically: https://github.com/janizde/WP-Opening-Hours/blob/master/doc/developer-guide.md#sets
