### ISSUE TITLE
open_text attribute of op-is-open shortcode stop working

### ISSUE THREAD

**Issue by ClaudioQ** [janizde/WP-Opening-Hours#83]
Hi,
I installed the new version of the plugin (2.1.12) after uninstalling the previous one (2.1.11).
During the business hours, the plugin shows "We're currently open." instead of the message in the open_text attribute of op-is-open shortcode.

It seemed to me that the message worked correctly in the previous version of the plugin, but I'm not sure (I tested it during closing hours).

I'm using the following shortcode:
`[op-is-open set_id="123" open_text"<strong>Al momento siamo aperti</strong>" closed_text="<strong>Al momento siamo chiusi</strong>" show_next="true" next_format="<em>Saremo aperti %2$s (%1$s) dalle %3$s alle %4$s</em>" date_format="d F Y" time_format="G:i"] `

The opening hours set (set_is="123") was created using the new version of the plugin.

(The pressage in next_format is displayed correctly during the closing hours)

**Comment by janizde** [comment]
Hi, it seems you missed an equal sign after the open_text in the shortcode. Please check

**Comment by ClaudioQ** [comment]
Hi,
you are right! I'm sorry, it was my mistake.

Thanks for your support.
