### ISSUE TITLE
Won't save my preset

### ISSUE THREAD

**Issue by RHOTELET** [janizde/WP-Opening-Hours#85]
Hi !
The plugin won't save my hours. By default it' with open from 12:00 Am to 12:00 AM, but if I change it, and click "Save", it won't save the hours i've changed !
Thank U for your help

**Comment by Braunson** [comment]
Same issue here.

**Comment by janizde** [comment]
@RHOTELET @Braunson This seems to be a misconception. AFAIK periods of 00:00 to 00:00 are discarded. I have added it to the Milestone Period Refactoring https://github.com/janizde/WP-Opening-Hours/milestone/2

**Comment by Braunson** [comment]
@janizde Regardless it never saves my hours in the backend, which makes this plugin useless to use.

**Comment by janizde** [comment]
Closing this one as it has probably been fixed with @Braunson PR in 2.1.3.
