### ISSUE TITLE
Is Open Widget and Shortcode show today always no work

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#86]
Is Open Widget and Is Open Shortcode show today only show today's opening hours when is open.

Always no work.

Thanks @janizde

**Comment by Braunson** [comment]
Same issue here, I've narrowed it down to the parameter `todays_string` from `classes/OpeningHours/Modules/Shortcode/IsOpen.php` function `shortcode` can't seem to properly apply filters to the line 79 and instead returns null which gets passed to the shortcodes `is-open.php` view.

**Comment by Braunson** [comment]
A temporary fix for this is to edit `classes/OpeningHours/Modules/CustomPostType/MetaBox/OpeningHours.php` just under line 66.. adding this:

```
        $dayConfig['start'][$i] = date('H:i', strtotime($dayConfig['start'][$i]));
        $dayConfig['end'][$i] = date('H:i', strtotime($dayConfig['end'][$i]));
```

The whole function..

```php
  public function getPeriodsFromPostData ( array $data ) {
    $periods = array();

    foreach ($data as $weekday => $dayConfig) {
      for ($i = 0; $i <= count($dayConfig['start']); $i++) {
        if (empty($dayConfig['start'][$i]) or empty($dayConfig['end'][$i]))
          continue;

        // TEMPORARY WORKAROUND FIX
        $dayConfig['start'][$i] = date('H:i', strtotime($dayConfig['start'][$i]));
        $dayConfig['end'][$i] = date('H:i', strtotime($dayConfig['end'][$i]));

        if ($dayConfig['start'][$i] === '00:00' and $dayConfig['end'][$i] === '00:00')
          continue;
          
        try {
          $period = new Period($weekday, $dayConfig['start'][$i], $dayConfig['end'][$i]);
          $periods[] = $period;
        } catch (\InvalidArgumentException $e) {
          trigger_error(sprintf('Period could not be saved due to: %s', $e->getMessage()));
        }
      }
    }

    return $periods;
  }
```

It's not the best but until a proper fix/decision is made it'll work to fix this issue and issue #85

**Comment by janizde** [comment]
Thanks for pointing out the error, I will fix it soon

**Comment by misagues** [comment]
I'm sorry, the widget does work.

I did not configure the widget correctly.

I did not write the Today' opening hours string (%1$s, %2$s or %3$s).

Sorry for the disturbances @janizde

**Comment by Braunson** [comment]
@janizde I'm having this same issue with Irregular hours too, they don't save. 😢

**Comment by janizde** [comment]
Thanks for pointing out @Braunson. Could you maybe branch from master and send a PR for this?

**Comment by Braunson** [comment]
@janizde will do

**Comment by janizde** [comment]
fixed in https://github.com/janizde/WP-Opening-Hours/pull/92
