### ISSUE TITLE
Removing borders from table

### ISSUE THREAD

**Issue by 2jaxx** [janizde/WP-Opening-Hours#87]
I would like to display the table without borders. I also have an issue where the left column is composed of only one cell, the upper right cell obviously contains that missing cell. 
Look here: https://www.scheiper-comtrainer.de

**Comment by janizde** [comment]
Hi @2jaxx ,
this is not specifically related to the plugin itself but rather to the theme you use. The overview table is displayed in your theme's default table design (which also includes that there are no borders in the weekday names, which is also specified in your theme's css).
To disable all borders to have to set `border: none` or even `border: none !important` for the selectors `table`,`table td` and `table th`. Mind that in this case all other tables will also loose borders. You can also use the `op-table` class to remove the borders only for the overview table.
