### ISSUE TITLE
Irregular opening hours in two columns?

### ISSUE THREAD

**Issue by 2jaxx** [janizde/WP-Opening-Hours#88]
I would like to display irregular opening hours without displaying the name of the particular entry. 
Using three columns in my sidebar causes display in two rows for the date. Analog to the overview, I would like to have the exact date on the left, opening hours on the right.
Using css for not showing empty cells is not applicable as there is no way to define an entry without a name. Is there any way to achieve this?

**Comment by janizde** [comment]
@2jaxx for now you can use a custom template with the template path filter: https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_shortcode_template.

As for the Overview with Dates theres currently only the option to interact with the OverviewModel API programatically. Then you will get instances of Weekday and have to translate them to the actual date context: https://github.com/janizde/WP-Opening-Hours/blob/master/classes/OpeningHours/Module/Shortcode/OverviewModel.php

**Comment by janizde** [comment]
But I will be offering a Template API for something like this in the future, currently don't have the time to do any development on the plugin itself

**Comment by 2jaxx** [comment]
Thanks a lot. I will look into that.
