### ISSUE TITLE
Days and Times options

### ISSUE THREAD

**Issue by dudgemaster** [janizde/WP-Opening-Hours#89]
Hi,
I am trying to change the format so that the Day and Time show on one line rather than in seperate boxes. i am happy to change the code for my site to do this but not sure where the time and day requests are pulled from.
in the long term an option to show this would be great.
![opening times](https://user-images.githubusercontent.com/30547701/28972377-5b0da0ea-7927-11e7-9157-14cc4a474089.jpg)
![screenshot](https://user-images.githubusercontent.com/30547701/28972439-90741bb0-7927-11e7-8c45-e02d02da6c36.jpg)

**Comment by dudgemaster** [comment]
So basically i want to move the call day hook in to the same line as the times

**Comment by janizde** [comment]
Hi @dudgemaster,
I am planning on a Template API to create any DOM you like from the Opening ours data but this will probably take some time. For the time being you have several options:

* Edit the plugin template file /views/shortcode/overview-list.php
* Use the table template and use custom styles
* Try to use custom CSS styles for the list template (this can be a bit tricky with <dl>)
* Use the OverviewModel API to get the data programatically. The OverviewModel class is not yet documented in the developers guide but you can read the PHP doc, I think it is quite explanatory: https://github.com/janizde/WP-Opening-Hours/blob/master/classes/OpeningHours/Module/Shortcode/OverviewModel.php

If you have any further questions please comment in this thread and mention me, I am closing this for now.

**Comment by janizde** [comment]
@dudgemaster There is another option which I consider the best: use the Shortcode Template filter which is documented here: https://github.com/janizde/WP-Opening-Hours/blob/master/doc/filters.md#op_shortcode_template

You can check for `$shortcode instanceof \OpeningHours\Module\Shortcode\Overview` and then specify a custom file path. Look at the overview template files in /views/shortcode/overview(-list).php to see what you get passed.
