### ISSUE TITLE
[Question] Separate Childset for all hoildays?

### ISSUE THREAD

**Issue by a3rosol** [janizde/WP-Opening-Hours#93]
We have different opening hours during school holidays. Is it possible to specify multiple dates for Child Sets? Or at least clone a child set?

**Comment by janizde** [comment]
@a3rosol what do you mean by multiple dates? You can specify a time range with the start and end date of the summer holidays. Cloning is possible through other plugins for WordPress e.g. https://de.wordpress.org/plugins/duplicate-post/. I haven't used it with opening hours but I think it should work

**Comment by a3rosol** [comment]
Like one set with regular hours and one set for _all_ holidays. It would be easier to specify all these holidays in the child set.
But thanks for the workaround :)

**Comment by janizde** [comment]
Ok so it would be something like recurring child sets. This is currently not available. Maybe I will add some kind of "pro" feature for it, but currently out of scope.
