### ISSUE TITLE
Please help me - Opening Hours

### ISSUE THREAD

**Issue by jacksonhass** [janizde/WP-Opening-Hours#94]
Please, how I change the color of title?
Now is Red, I need change to WHITE/BOLD.
See the image.

Thanks and congratulations for the plugin.
![captura de tela 2017-08-23 as 11 51 28](https://user-images.githubusercontent.com/31285128/29625455-b7d0f6a2-87f9-11e7-9ff5-71cdc8c819af.jpg)

**Comment by janizde** [comment]
Hi @jacksonhass the plugin uses your theme's standard sidebar heading styles. You will have to change the style of your theme's headings with CSS (or specify a selector only for the opening hours heading).

```
.insert-your-heading-class {
  color: white;
  font-weight: bold;
}
```
