### ISSUE TITLE
op overview holiday, off by one day

### ISSUE THREAD

**Issue by JesperStender** [janizde/WP-Opening-Hours#97]
When i set my holidays to my tuesday this week, it shows it on monday in the overview 
Meaning that it displays that the holiday is 1 day before the actual day.
- also, it does not overwrite the op-is-open when that day arrives? 

my shortcodes, 
is-open  : <?php echo do_shortcode( ' [op-is-open set_id="openinghours" open_text="Åbent i dag" closed_text="Åbent i dag" show_today=open] ' );?> 

op-overview : echo do_shortcode( ' [op-overview set_id="openinghours" highlight="day" title="Butikker" time_format="H:i" include_holidays=true include_io=true hide_io_date=true ] ' )

I have no childsets overwriting my tables.

I have tried different things now, but nothing seems to get me closer to fixing this - am i doing anything wrong in my shortcodes? or is this a bug in the newest versions?  I tried updating it.

**Comment by janizde** [comment]
Hi @JesperStender ,
maybe you've already come across this but I always ask to be sure: Have you checked your timezone and start of week settings in WordPress' `Settings > General`?

**Comment by JesperStender** [comment]
okay, so i found the problem, and i am pretty sure that it has nothing to do with your plugin :) 
In one of my template files, it is setting default timezone to copenhagen, and even though the general settings is also set to copenhagen, it screws up the date for your plugin. 

In my mind it should not effect each other, but somehow it does.
meaning that I will have to make new time and date calculations for the template that does it.

I mean, it is just setting the same timezone twice - how should that put it of by a full day :/ 

Thank you for your suggestion - i am closing since it probably does have nothing to do with your plugin.

**Comment by janizde** [comment]
WordPress sets the PHP timezone to UTC and calculates the tz you set up on top of UTC. So setting the default timezone will break WP

**Comment by JesperStender** [comment]
thank you! 
I guess that you would know about how WP sets its time.

If anybody reads this in the future and needs it.
My fix was, instead of setting timezone, just calculating with the offset like WP does : 
time() + (1 * 2 * 60 * 60); // adding two hours to UTC time.

**Comment by janizde** [comment]
afaik, [`current_time`](https://developer.wordpress.org/reference/functions/current_time/) will do the same but adjusted to the timezone setting that you have actually made in the WP settings

**Comment by Rhatur** [comment]
Hello, I am facing the same issue but I don't understand how to set the time.
I have added this code:
`
add_action('woocommerce_after_order_notes', 'ad_dev_display_opening_hours_on_checkout');
function ad_dev_display_opening_hours_on_checkout()
{
    echo do_shortcode('[op-overview set_id="5114" show_closed_days="true" highlight="day" compress="true" include_io="true" include_holidays="true"]');
}
`
to my function.php file in the child theme. 
How can I set up the current_time right before displaying the shortcode?

Thanks for your help!
