### ISSUE TITLE
Irregular Hours "Closed" Option Request

### ISSUE THREAD

**Issue by k3v1np** [janizde/WP-Opening-Hours#99]
Either a check box on an irregular hour entry to over ride regular hours as closed or by entering 0:00 for open and closed and  displays as closed for that day.

**Comment by k3v1np** [comment]
I guess you can always use the Holiday section to set specific days as closed.

**Comment by janizde** [comment]
@k3v1np yes indeed, and as you don't have regular hours on that day (as I understood in your other issue) you don't have to specify anything and it will automatically be closed
